const wordStructure = [
  {
    principle:
      "The letter i in the 1st form changes to a in the 2nd, to u in the 3rd",
    wordList: [
      ["ring", "rang", "rung"],
      ["sing", "sang", "sung"],
      ["sink", "sank", "sunk"],
      ["drink", "drank", "drunk"],
      ["shrink", "shrank", "shrunk"],
      ["swim", "swam", "swum"],
      ["begin", "began", "begun"],
      ["run", "ran", "run"],
    ],
  },
  {
    principle: `1. The long sound /iː/ in the 1st form is shorted to short /e/ in the 2nd and 3rd 
2. The letter e in the 1st form changes in the 2nd and 3rd to o (or vice versa), and the last letter to d`,
    wordList: [
      ["feed", "fed", "fed"],
      ["lead", "led", "led"],
      ["breed", "bred", "bred"],
      ["read", "read", "read"],
      ["sell", "sold", "sold"],
      ["tell", "told", "told"],
      ["hold", "held", "held"],
    ],
  },
  {
    principle: "The 1st, 2nd, 3rd form are one word",
    wordList: [
      ["hit", "hit", "hit"],
      ["fit", "fit", "fit"],
      ["spit", "spit", "spit"],
      ["knit", "knit", "knit"],
      ["quit", "quit", "quit"],
      ["let", "let", "let"],
      ["set", "set", "set"],
      ["upset", "upset", "upset"],
      ["shut", "shut", "shut"],
      ["cut", "cut", "cut"],
      ["put", "put", "put"],
      ["cost", "cost", "cost"],
      ["hurt", "hurt", "hurt"],
      ["spread", "spread", "spread"],
      ["cast", "cast", "cast"],
      ["broadcast", "broadcast", "broadcast"],
    ],
  },
  {
    principle: "The 2nd and 3nd forms end in -ought",
    wordList: [
      ["buy", "bought", "bought"],
      ["fight", "fought", "fought"],
      ["seek", "sought", "sought"],
      ["think", "thought", "thought"],
      ["bring", "brought", "brought"],
      ["teach", "taught", "taught"],
      ["catch", "caught", "caught"],
    ],
  },
  {
    principle: `1. In the 2nd and 3rd forms the last letter changes to t
2. In the 2-nd and 3-rd forms, the letter t is added at the end, and letter combination ee and ea usually changes to e`,
    wordList: [
      ["bend", "bent", "bent"],
      ["send", "sent", "sent"],
      ["lend", "lent", "lent"],
      ["spend", "spent", "spent"],
      ["build", "built", "built"],
      ["lose", "lost", "lost"],
      ["sleep", "slept", "slept"],
      ["keep", "kept", "kept"],
      ["creep", "crept", "crept"],
      ["weep", "wept", "wept"],
      ["sweep", "swept", "swept"],
      ["feel", "felt", "felt"],
      ["meet", "met", "met"],
      ["leap", "leapt", "leapt"],
      ["leave", "left", "left"],
      ["mean", "meant", "meant"],
      ["dream", "dreamt", "dreamt"],
      ["burn", "burnt", "burnt"],
    ],
  },
  {
    principle:
      "In the 2-nd and 3-rd forms the vowels change; in some cases y changes to id",
    wordList: [
      ["hang", "hung", "hung"],
      ["dig", "dug", "dug"],
      ["stand", "stood", "stood"],
      ["understand", "understood", "understood"],
      ["stick", "stuck", "stuck"],
      ["strike", "struck", "struck"],
      ["sit", "sat", "sat"],
      ["win", "won", "won"],
      ["shoot", "shot", "shot"],
      ["make", "made", "made"],
      ["pay", "paid", "paid"],
      ["lay", "laid", "laid"],
      ["say", "said", "said"],
      ["light", "lit", "lit"],
      ["find", "found", "found"],
    ],
  },
  {
    principle: "The 2-nd form ends in -ew, and the 3-rd in -own",
    wordList: [
      ["throw", "threw", "thrown"],
      ["grow", "grew", "grown"],
      ["blow", "blew", "blown"],
      ["draw", "drew", "drawn"],
      ["withdraw", "withdrew", "withdrawn"],
      ["fly", "flew", "flown"],
      ["know", "knew", "known"],
    ],
  },
  {
    principle:
      "The 3-rd form ends in -en; in the 2-nd form, the vowels at the root in more cases change to o, oo and a",
    wordList: [
      ["choose", "chose", "chosen"],
      ["freeze", "froze", "frozen"],
      ["wake", "woke", "woken"],
      ["awake", "awoke", "awoken"],
      ["break", "broke", "broken"],
      ["steal", "stole", "stolen"],
      ["fall", "fell", "fallen"],
      ["write", "wrote", "written"],
      ["ride", "rode", "ridden"],
      ["drive", "drove", "driven"],
      ["rise", "rose", "risen"],
      ["shake", "shook", "shaken"],
      ["take", "took", "taken"],
      ["overtake", "overtook", "overtaken"],
      ["mistake", "mistook", "mistaken"],
      ["get", "got", "gotten"],
      ["forget", "forgot", "forgotten"],
      ["hide", "hid", "hidden"],
      ["bite", "bit", "bitten"],
      ["beat", "beat", "beaten"],
      ["eat", "ate", "eaten"],
      ["swear", "swore", "sworn"],
      ["tear", "tore", "torn"],
      ["wear", "wore", "worn"],
      ["give", "gave", "given"],
      ["forgive", "forgave", "forgiven"],
      ["forbid", "forbade", "forbidden"],
      ["prove", "proved", "proven"],
      ["shave", "shaved", "shaven"],
      ["show", "showed", "shown"],
      ["weave", "wove", "woven"],
    ],
  },
  {
    principle: "Verb that don't fit into any pattern",
    wordList: [
      ["dive", "dived", "dove", "dived"],
      ["do", "did", "done"],
      ["go", "went", "gone"],
      ["hear", "heard", "heard"],
      ["have", "had", "had"],
      ["be", "am", "is", "are", "was", "were", "been"],
      ["come", "came", "come"],
      ["become", "became", "become"],
      ["overcome", "overcame", "overcome"],
      ["see", "saw", "seen"],
      ["slide", "slid", "slid"],
      ["saw", "sawed", "sawn", "sawed"],
      ["lie", "lied", "lied"],
      ["lie", "lay", "lain"],
      ["lay", "laid", "laid"],
    ],
  },
]

export default wordStructure
